---
- hosts: database
  become: true
  tasks:
    - name: Install mysql-server
      yum: name=mysql-server state=present

    - name: Ensure services are started and enabled
      service: name=mysql state=started enabled=yes
