---
- hosts: loadbalancer
  become: true  
  tasks:
    - name: Install tools
      apt: name={{item}} state=present 
      with_items:
        - python-httplib2

    - name: Install nginx
      apt: name=nginx state=present update_cache=yes

    - name: Ensure nginx is started
      service: name=nginx state=started enabled=yes

    - name: Configure Nginx 2 backend
      template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0644
      notify:  restart nginx

    - name: Deactivate old nginx backend
      file: path=/etc/nginx/sites-available/default state=absent mode=0644
      notify: restart nginx
    
    - name: Activate new nginx backend
      file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link mode=0644
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
