---
- hosts: loadbalancer
  tasks:
  - name: Check nginx is running
    command: service nginx status

  - name: Check nginx is listening on port 80
    wait_for: port=80 timeout=1

- hosts: database
  tasks:
  - name: Check mysql is running
    command: service mysql status

  - name: Check mysql is listening on port 3306
    wait_for: port=3306 timeout=1

- hosts: webserver
  tasks:
  - name: Check apache2 is running
    command: service apache2 status

  - name: Check apache2 is listening on port 80
    wait_for: port=80 timeout=1

- hosts: control
  tasks:
  - name: End to end app verification
    uri: url=http://{{item}} return_content=yes
    with_items: 
      - groups.loadbalancer
    register: lb_index

  - fail: msg="Index failed to return content"
    when: "'Hello, from sunny' not in item.content"
    with_items: "{{lb_index.results}}"
