---
- hosts: webserver
  become: true
  tasks:
    - name: install apache2
      apt: name={{item}} state=present
      with_items:
       - apache2
       - libapache2-mod-wsgi 
       - python-pip 
       - python-virtualenv 

    - name: Enable apache
      service: name=apache2 state=started enabled=yes

    - name: ensure mod_wsgi enabled
      apache2_module: state=present name=wsgi
      notify: restart apache2

  handlers:
    - name: Restart Apache2
      service: name=apache2 state=restarted
