---
# tasks file for database
  - name: Install tools
    apt: name={{item}} state=present update_cache=yes
    with_items:
    - python-mysqldb

  - name: Install mysql-server
    apt: name=mysql-server state=present

  - name: Ensure services are started and enabled
    service: name=mysql state=started enabled=yes

  - name: Ensure MySQL listening on all ports
    lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
              line="bind-address = {{ ansible_eth0.ipv4.address }}"
    notify: restart mysql

  - name: Create demo database
    mysql_db: name={{ db_name }} state=present

  - name: Create demo user
    mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{ db_name }}.*:ALL 
                host='{{ db_user_host }}' state=present
