---
# tasks file for database
tasks:
  - name: Install tools
    apt: name={{item}} state=present update_cache=yes
    with_items:
    - python-mysqldb

  - name: Install mysql-server
    apt: name=mysql-server state=present

  - name: Ensure services are started and enabled
    service: name=mysql state=started enabled=yes

  - name: Ensure MySQL listening on all ports
    lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
              line="bind-address = 0.0.0.0"
    notify: restart mysql

  - name: Create demo database
    mysql_db: name=demo state=present

  - name: Create demo user
    mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present
